### ISSUE TITLE
Determine UC / Mainline Split

### ISSUE THREAD

**Issue by austinEng** [GraceCovenantChurch/gccweb#19]
We need to figure out how we want to split Mainline and UC content. There are a few possible options that I see:
1. Have identical sites running on separate subdomains
2. Have identical sites on the same domain but something like gracecovenant.net/uc and gracecovenant.net/mainline
3. Have just one site with separate pages / sections for mainline and uc content
4. Don't separate anything at all

`1` and `2` are essentially the same solution with just cosmetic differences, but `1` is probably just slightly simpler on the implementation for routing reasons.

`3` Seems like the easiest option if only announcement content is different. Will there be more things different? Different family group pages, etc.?

`4`  is even easier than `3` and is sort of motivated by the idea that our church is sort of two separate churches and there isn't really much awareness of the other half. Maybe we should intentionally not maintain a separation of content. Not sure if this is something we actually care about.

@joeyzia can you discuss with leadership and figure out what they think would be best?

**Comment by joeyzia** [comment]
Closing this for now -- This will probably reopen in the future.
