### ISSUE TITLE
Fix Main Announcement Admin Panel

### ISSUE THREAD

**Issue by austinEng** [GraceCovenantChurch/gccweb#20]
Submitting the form on the admin panel no longer works. This is likely due to a move from Angular 1 to Angular 2. Angular 2 captures and does `preventDefault` on the default form handler

**Comment by jayjung1018** [comment]
yes - sorry austin. I was in the middle of fixing this when i stopped working on it. let me know if i can explain anything. i tried to model it off of your work as much as possible.

**Comment by austinEng** [comment]
@jayjung1018 I think #21 fixes it. Just want @crchong1 to review it so he understands what's going on. But you could take a look as well to check things.
