### ISSUE TITLE
TitleBanner Component: Center Image

### ISSUE THREAD

**Issue by joeyzia** [GraceCovenantChurch/gccweb#36]
When the screen is decreased, the original image of the banner isn't centered. Intent is for it to be centered.

![screen shot 2017-11-07 at 7 44 14 pm](https://user-images.githubusercontent.com/29345616/32525809-2f36583c-c3f4-11e7-9b84-5c7e8d3bd408.png)

**Comment by austinEng** [comment]
Should this be centered both vertically and horizontall? @joeyzia

**Comment by joeyzia** [comment]
Maybe we can give that option since every image will always be different?
