### ISSUE TITLE
Navigation Bar: Persistence

### ISSUE THREAD

**Issue by joeyzia** [GraceCovenantChurch/gccweb#38]
The navigation bar currently is not persistent as you scroll through the page. We want it so that as we scroll through the page we can see the menu throughout the page.

![screen shot 2017-11-07 at 7 49 09 pm](https://user-images.githubusercontent.com/29345616/32525960-f8d8dc64-c3f4-11e7-949b-96302420bb3a.png)

![screen shot 2017-11-07 at 7 49 29 pm](https://user-images.githubusercontent.com/29345616/32525970-06f45b02-c3f5-11e7-9f75-7aa34408baff.png)

<img width="787" alt="screen shot 2017-11-07 at 7 49 36 pm" src="https://user-images.githubusercontent.com/29345616/32525974-099bf40a-c3f5-11e7-9541-b6d769bc1e10.png">

**Comment by austinEng** [comment]
@estheryjeon Do we have ideas on how this should look? Right now the nav bar is transparent, but if it is persistent and stays at the top, it's going to need to have an opaque background or have one transition in.

**Comment by estheryjeon** [comment]
@austinEng Hmm. I'm going to try some things. Tried the transition in and it looks a little out of place.
