### ISSUE TITLE
I'm New: Google Map API

### ISSUE THREAD

**Issue by joeyzia** [GraceCovenantChurch/gccweb#39]
We want to be able to provide a google map of the locations that we're using. There are technically two things that needs to be done.

1. Implementing the Google map API into the page so that we can see the two locations.
2. Making sure the API key we're using isn't expired.

![screen shot 2017-11-07 at 7 53 01 pm](https://user-images.githubusercontent.com/29345616/32526078-85574bda-c3f5-11e7-8225-50fba08bf029.png)

![screen shot 2017-11-07 at 7 53 17 pm](https://user-images.githubusercontent.com/29345616/32526085-8a57a26a-c3f5-11e7-8624-ce68af388748.png)

**Comment by austinEng** [comment]
@joeyzia Do we have an existing google account for the church? I can look into the API keys and such

**Comment by joeyzia** [comment]
Check out our drive. Created a google account for us to use.
