### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by estheryjeon** [GraceCovenantChurch/gccweb#65]
All buttons should be -
width: 200px;
height: 50px;

all text in buttons should follow styles for all other text (font-weight: 300; font-size: 1em;)

**Comment by vce23** [comment]
I fixed the width and height and addressed the size and boldness of things.

I ran into an issue where .title is being inherited into .infoButton, so I had to hardcode things to reach a solution. This may need .subtitle and .infoButton to be separated, but I didn't want to do that without saying what I finished.
