### ISSUE TITLE
Set Page Titles

### ISSUE THREAD

**Issue by jayjung1018** [GraceCovenantChurch/gccweb#9]

**Comment by joeyzia** [comment]
Yeah, this needs to have proper the <title> ____ </title> since it's saying Grace Covenant Church for each page. I don't actually now if it's <title> ___ </title>... but we need to have Grace Covenant Church - Family Group as an example

**Comment by jayjung1018** [comment]
yup this was just a todo list kind of thing for me - easy changes.

**Comment by joeyzia** [comment]
We finished this since this is already done in React. Closing.
